language: cpp
before_script:
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T bulk.deb -unikita-chizh:$BINTRAY_API_KEY "https://api.bintray.com/content/nikita-chizh/Otus/bulk/$TRAVIS_BUILD_NUMBER/bulk.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"